name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Explain what you were doing, what you expected to happen, and what actually happened. The more details you provide, the better we can help you!
      placeholder: Describe the bug here
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browsers did you run into this issue on?
      multiple: true
      options:
        - Not a browser issue
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: true

