name: Deploy to AWS Lambda
on: 
  workflow_dispatch:
  push:
    paths:
      - 'lambda/**'
      - '.github/workflows/main.yml'
jobs:
  auth:
    name: Build sync script Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
      - name: Setting up environment
        run: |
          python -m pip install --upgrade pip
          cd lambda/sync
          pip3 install -r requirements.txt -t .
          zip -r lambda-env.zip .
      - name: Deploying to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION_NAME }}
          function_name: AniMalSync-Script
          zip_file: lambda/sync/lambda-env.zip
          environment: >
            APP_EMAIL=animalsync.app@gmail.com,
            LOG_LEVEL=INFO,
            AWS_USER_DYNAMODB_TABLE=AniMalSync-User-Data,
            AWS_SYNC_LOG_DYNAMODB_TABLE=AniMalSync-Sync-Log,
            AWS_SFN_ARN=arn:aws:states:us-east-2:983398483317:stateMachine:AniMalSync-Sync-Publish
  email:
    name: Build email MAL authorization Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
      - name: Deploying to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION_NAME }}
          function_name: AniMalSync-OAuth-Emailer
          source: lambda/email/email_lambda.py
          environment: >
            APP_EMAIL=animalsync.app@gmail.com,
            AUTH_EMAIL_TEMPLATE=AniMalSync_MAL_Auth,
            AWS_USER_DYNAMODB_TABLE=AniMalSync-UserData
