name: Deploy Sync Script
on: 
  workflow_dispatch:
  push:
    paths:
      - 'lambda/sync/**'
      - '.github/workflows/main.yml'
jobs:
  sync:
    name: Build and deploy sync script Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
      - name: Setting up environment
        run: |
          python -m pip install --upgrade pip
          cd lambda/sync
          pip3 install -r requirements.txt -t .
          zip -r lambda-env.zip .
      - name: Deploying to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION_NAME }}
          function_name: AniMalSync-Script
          zip_file: lambda/sync/lambda-env.zip

name: Deploy MAL Auth Email Script
on: 
  workflow_dispatch:
  push:
    paths:
      - 'lambda/email/**'
      - '.github/workflows/main.yml'
  email:
    name: Build and deploy email MAL authorization Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
      - name: Deploying to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION_NAME }}
          function_name: AniMalSync-OAuth-Emailer
          source: lambda/email/email_lambda.py


name: Deploy Web App to Elastic Beanstalk
on: 
  workflow_dispatch:
  push:
    paths:
      - 'web/**'
      - '.github/workflows/main.yml'
  email:
    name: Build and deploy webapp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Generate deployment package
        run: |
          cd web/
          zip -r app.zip .
      - name: Deploying to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION_NAME }}
          application_name: AniMalSync
          environment_name: Animalsync-env
          deployment_package: web/app.zip
